apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: ansalsajan/postgres:app
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: data
        - name: POSTGRES_USER
          value: ubuntu
        - name: POSTGRES_PASSWORD
          value: ansal
