apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres  # This should match the label of your PostgreSQL pod or deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
