apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
  - name: output
  params:
  - name: url
    type: string
  - name: revision
    type: string
  steps:
  - name: clone
    image: alpine/git
    script: |
      set -ex
      cd $(workspaces.output.path)
      git clone $(params.url) .
      git checkout $(params.revision)
      ls
      cat Dockerfile