FROM postgres:14.11

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=ubuntu
ENV POSTGRES_PASSWORD=ansal
ENV POSTGRES_DB=data

# Expose PostgreSQL default port
EXPOSE 5432

# By default, listen on all interfaces (0.0.0.0)
CMD ["postgres", "-c", "listen_addresses=*"]

